#!/bin/sh

set -e

APP=ubuntu-tweak

VERSION=`cd ~/Sources/ubuntu-tweak && python -c 'import ubuntutweak;print ubuntutweak.__version__'`

BUILD_ROOT=$HOME/Sources/$APP/dist

rm -rf $BUILD_ROOT

for DISTRO in oneiric precise quantal;do
    release-build $APP $VERSION $DISTRO
done
