#!/bin/sh


if [ -n "$1" ];then
	APPLICATION=$1
else
	APPLICATION=ubuntu-tweak
fi

if [ -n "$2" ];then
	VERSION=$2
else
	VERSION=0.4.7
fi

if [ -n "$3" ];then
	DISTRO=$3
else
	DISTRO=hardy
fi

VERSION=$2
DISTRO=$3

SRC_ROOT=$HOME/Sources/$APPLICATION
BUILD_ROOT=$HOME/Sources/$APPLICATION/dist
BUILD_DIR=$BUILD_ROOT/$APPLICATION-$VERSION
TARBALL=$BUILD_ROOT/$APPLICATION-$VERSION.tar.gz
ORIGBALL=$BUILD_ROOT/${APPLICATION}_${VERSION}.orig.tar.gz
CHANGELOG=$HOME/Sources/ubuntu-tweak-0.7.x-packaging/debian/changelog

CLEAN_OLD() {
	rm -rf $BUILD_DIR
}

CLEAN_OLD

INFO() {
	echo "Building $APPLICATION-$VERSION for $DISTRO at $BUILD_DIR"
}
INFO

cd $SRC_ROOT

if [ ! -e $ORIGBALL ];then
	python setup.py sdist > /dev/null
	mv -v $TARBALL $ORIGBALL
fi

tar zxf $ORIGBALL -C $BUILD_ROOT/
cp -r $SRC_ROOT/debian $BUILD_DIR/debian

REPLACE=`head -1 $CHANGELOG | grep $DISTRO`

if [ ! -n "$REPLACE" ]; then
	echo "Replace the maverick with $DISTRO"
	sed -i "1s/precise/$DISTRO/g" $CHANGELOG
fi

cp -rv $CHANGELOG $BUILD_DIR/debian/changelog

cd $BUILD_DIR
debuild -S -sa > /dev/null
